<?php
    include "setup_session.php";
    if(isset($_GET['case1'])){
        $_SESSION['cart'][0]++;
        header("location:../IE4717-Design-Project/case.php");
    }elseif(isset($_GET['case2'])){
        $_SESSION['cart'][1]++;
        header("location:../IE4717-Design-Project/case.php");
    }elseif(isset($_GET['case3'])){
        $_SESSION['cart'][2]++;
        header("location:../IE4717-Design-Project/case.php");
    }elseif(isset($_GET['case4'])){
        $_SESSION['cart'][3]++;
        header("location:../IE4717-Design-Project/case.php");
    }elseif(isset($_GET['watch1'])){
        $_SESSION['cart'][4]++;
        header("location:../IE4717-Design-Project/smartwatch.php");
    }elseif(isset($_GET['watch2'])){
        $_SESSION['cart'][5]++;
        header("location:../IE4717-Design-Project/smartwatch.php");
    }elseif(isset($_GET['watch3'])){
        $_SESSION['cart'][6]++;
        header("location:../IE4717-Design-Project/smartwatch.php");
    }elseif(isset($_GET['watch4'])){
        $_SESSION['cart'][7]++;
        header("location:../IE4717-Design-Project/smartwatch.php");
    }elseif(isset($_GET['airpod1'])){
        $_SESSION['cart'][8]++;
        header("location:../IE4717-Design-Project/airpod.php");
    }elseif(isset($_GET['airpod2'])){
        $_SESSION['cart'][9]++;
        header("location:../IE4717-Design-Project/airpod.php");
    }elseif(isset($_GET['airpod3'])){
        $_SESSION['cart'][10]++;
        header("location:../IE4717-Design-Project/airpod.php");
    }elseif(isset($_GET['airpod4'])){
        $_SESSION['cart'][11]++;
        header("location:../IE4717-Design-Project/airpod.php");
    }elseif(isset($_GET['iphone14pro']) && isset($_GET['128GB'])){
        $_SESSION['cart'][12]++;
        header("location:../IE4717-Design-Project/phone.php");
    }

